### ISSUE TITLE
Microsoft Powershell issue

### ISSUE THREAD

**Issue by mondex111** [BasuCert/WinboxPoC#41]
Last 1 Keys:
 UpArrow

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by Deantwo** [comment]
Didn't know Powershell could run Python.

What is the issue here? Looks like an .Net `System.ArgumentOutOfRangeException` exception, so what arguments did you give the script?

Please supply:
- Full command and arguments used to call the script.
- RouterOS version of your MikroTik router.

**Comment by mosajjal** [comment]
this does not look like an issue with this project. closing
