### ISSUE TITLE
extract_user not working on 6.41.4

### ISSUE THREAD

**Issue by Tarikxmx** [BasuCert/WinboxPoC#7]
Traceback (most recent call last):
  File "C:\Python37\extract_user.py", line 57, in <module>
    dump(user_file)
  File "C:\Python37\extract_user.py", line 45, in dump
    user_pass = get_pair(data)
  File "C:\Python37\extract_user.py", line 38, in get_pair
    user  = user.decode("ascii")
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8d in position 34: ordinal not in range(128)

**Comment by BigNerd95** [comment]
I need the affected user.dat file to investigate

**Comment by jomp16** [comment]
It's because of accentuation in the username.  Like "josé".
That isn't ascii, I've tried changing to utf8, it didn't work, I changed to iso8859-1, still nothing. So what I did is printing everything until it breaks on the user that has accentuation.
